# Generated by Django 3.2.18 on 2023-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='course_images/'),
        ),
    ]
